dataset:
    root: "dataset/instacart/data"
    max_seq: 64
    max_set_size: 32
trainer:
    lr: 0.00005
    batch_size: 8
    epochs: 1
    split: [0.90, 0.10]
    early_stopping_patience: 5
    early_stopping_mode: 'min'
    mlm_probability: 0.15
model:
    tokenizer: "dataset/instacart/data/tk.json"
    t2v_scale: 1.0
    d_model: 256
    n_heads: 4
    d_ff: 756
    n_block: 2
    dropout: 0.0
    weight_tying: true
    attn_backend: "efficient_attention"
