dataset:
    data_root: "/work/ms1008/instacart"
    max_seq: 64
    max_set_size: 32
    seq_id_col: "user_id"
    set_id_col: "order_number"
    token_col: "product_id"
    val_col: null
    additional_cols: ["t"]
trainer:
    lr: 0.00005
    batch_size: 16
    epochs: 20
    split: [0.90, 0.10]
    early_stopping_patience: 5
    early_stopping_mode: 'max'
    mlm_probability: 0.20
    softclt:
      tau_temp: 2
      lambda_: 0.5
      alpha: 0.5
    eval_last_set: true
    l_mlm: 1
    l_softclt: 1
model:
    tokenizer: "dataset/instacart/data/tk.json"
    t2v_scale: 1.0
    d_model: 768
    n_heads: 12
    d_ff: 2048
    n_block: 6
    dropout: 0.1
    norm_type: "layer"
    ffn_type: "swiglu"
    weight_tying: true
    attn_backend: "efficient_attention"
